backend:
  name: github
  repo: apurbo26/livebdth  # আপনার GitHub ইউজারনেম/রিপোজিটরি
  branch: main
  base_url: https://api.netlify.com
  auth_scope: repo
  site_url: https://helpful-baklava-016ed1.netlify.app  # <--- নতুন যোগ করা হয়েছে
  display_url: https://helpful-baklava-016ed1.netlify.app # <--- নতুন যোগ করা হয়েছে

media_folder: "assets/images" 
public_folder: "/assets/images"

collections:
  - name: "channels" 
    label: "Live TV Channels"
    folder: "/"
    file: "channels_data.json" 
    format: json
    editor:
      preview: false
    fields:
      - label: "Channel List"
        name: "items"
        widget: "list"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Logo URL"
            name: "logo"
            widget: "string"
          - label: "Stream URL (M3U8/HLS)"
            name: "url"
            widget: "string"
            
